language: cpp
compiler: g++

before_script:
    - sudo apt-get install libboost-test-dev
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update
    - sudo apt-get install g++-5 -y
    - cd test

script: make test
